### ISSUE TITLE
can't get the wallust template to work on linux.

### ISSUE THREAD

**Issue by thenameofallnames-ig** [Gremious/discord-wal-theme-template#3]
no matter how i write that entry in the wallust.toml file, it doesn't get read at all from it.
this is how i have it written.
`vencord = { template = '/home/giuls/.config/wallust/discord-wallust-beta.css', target = '/home/giuls/.config/Vencord/themes/wallust.css' }`
i'm using the v3 beta, if it helps.

**Comment by Gremious** [comment]
Oh, yep, my mistake. 

It's
```toml
[templates]
vencord = { template = 'source', target = 'destination' }
```

Note the `[templates]`, starting a template seciton.

or alternatively:

```toml
[templates.vencord]
template = 'source'
target = 'destination'
```

 I'll fix the readme in a min.
